# Generated by Django 2.1.1 on 2018-12-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PickSetModel',
            new_name='PickSet',
        ),
    ]
