# Generated by Django 2.1.2 on 2018-12-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_auto_20181227_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickset',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
