# Generated by Django 2.1.2 on 2019-01-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_pickset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickset',
            name='round_1_game_1_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickset',
            name='round_1_game_2_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickset',
            name='round_1_game_3_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickset',
            name='round_1_game_4_team',
            field=models.IntegerField(default=1),
        ),
    ]
