# Generated by Django 2.1.2 on 2019-01-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0006_pickset_results_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickset',
            name='wc_game_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickset',
            name='wc_game_1_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickset',
            name='wc_game_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickset',
            name='wc_game_2_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickset',
            name='wc_game_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickset',
            name='wc_game_3_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickset',
            name='wc_game_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickset',
            name='wc_game_4_team',
            field=models.IntegerField(default=1),
        ),
    ]
