# Generated by Django 2.1.2 on 2019-01-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0007_auto_20190107_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickset',
            name='round_2_game_1',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='pickset',
            name='round_2_game_1_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pickset',
            name='round_2_game_2',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pickset',
            name='round_2_game_2_team',
            field=models.IntegerField(default=1),
        ),
    ]
