# Generated by Django 2.1.2 on 2019-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0008_added_round_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickset',
            name='super_bowl_pick',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pickset',
            name='super_bowl_team',
            field=models.IntegerField(default=0),
        ),
    ]
